# Generated by Django 4.2.6 on 2023-10-09 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('C', 'School'), ('S', 'Student')], default='S', max_length=5),
        ),
    ]
