# Generated by Django 4.2.6 on 2023-10-10 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('C', 'School'), ('S', 'Student'), ('SU', 'Superuser')], default='S', max_length=5),
        ),
    ]
